# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Question1_GDCD_GKI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
class Ui_Question1_GDCD_GKI(QtWidgets.QWidget):
    def __init__(self,name):
        super().__init__()
        self.name = name
        self.count = 1800
        self.total = 0

    def setupUi(self, Question1_GDCD_GKI):
        Question1_GDCD_GKI.setObjectName("Question1_GDCD_GKI")
        Question1_GDCD_GKI.resize(1081, 702)
        Question1_GDCD_GKI.setMinimumSize(QtCore.QSize(1081, 702))
        Question1_GDCD_GKI.setMaximumSize(QtCore.QSize(1081, 702))
        self.centralwidget = QtWidgets.QWidget(Question1_GDCD_GKI)
        self.centralwidget.setObjectName("centralwidget")
        self.D_Button = QtWidgets.QRadioButton(self.centralwidget)
        self.D_Button.setGeometry(QtCore.QRect(20, 450, 1061, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.D_Button.setFont(font)
        self.D_Button.setObjectName("D_Button")
        self.Time = QtWidgets.QLineEdit(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(700, 20, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        self.Time.setFont(font)
        self.Time.setObjectName("Time")
        self.C_Button = QtWidgets.QRadioButton(self.centralwidget)
        self.C_Button.setGeometry(QtCore.QRect(20, 370, 1061, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.C_Button.setFont(font)
        self.C_Button.setObjectName("C_Button")
        self.Next_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Next_Button.setGeometry(QtCore.QRect(270, 550, 551, 101))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.Next_Button.setFont(font)
        self.Next_Button.setStyleSheet("\n"
"QPushButton#Next_Button{\n"
"    background-color: rgb(212, 212, 212);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"}\n"
"QPushButton#Next_Button:pressed{\n"
"padding-left: 2px;\n"
"padding-right: 2px;\n"
"    background-color: rgb(171, 171, 171);\n"
"}")
        self.Next_Button.setObjectName("Next_Button")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 20, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Name = QtWidgets.QLineEdit(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(80, 20, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        self.Name.setFont(font)
        self.Name.setObjectName("Name")
        self.B_Button = QtWidgets.QRadioButton(self.centralwidget)
        self.B_Button.setGeometry(QtCore.QRect(20, 290, 1061, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.B_Button.setFont(font)
        self.B_Button.setObjectName("B_Button")
        self.A_Button = QtWidgets.QRadioButton(self.centralwidget)
        self.A_Button.setGeometry(QtCore.QRect(20, 210, 1061, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.A_Button.setFont(font)
        self.A_Button.setObjectName("A_Button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 1071, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        Question1_GDCD_GKI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Question1_GDCD_GKI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 21))
        self.menubar.setObjectName("menubar")
        Question1_GDCD_GKI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Question1_GDCD_GKI)
        self.statusbar.setObjectName("statusbar")
        Question1_GDCD_GKI.setStatusBar(self.statusbar)
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.ShowTime)
        self.timer.start(1000)
        self.retranslateUi(Question1_GDCD_GKI)
        QtCore.QMetaObject.connectSlotsByName(Question1_GDCD_GKI)

    def retranslateUi(self, Question1_GDCD_GKI):
        _translate = QtCore.QCoreApplication.translate
        Question1_GDCD_GKI.setWindowTitle(_translate("Question1_GDCD_GKI", "MainWindow"))
        self.D_Button.setText(_translate("Question1_GDCD_GKI", "D. Tạo ra cơm ăn, áo mặc, tạo ra tư liệu sản xuất."))
        self.C_Button.setText(_translate("Question1_GDCD_GKI", "C. Con người tác động vào tự nhiên để tạo ra các sản phẩm phù hợp với như cầu của mình."))
        self.Next_Button.setText(_translate("Question1_GDCD_GKI", "PushButton"))
        self.label_4.setText(_translate("Question1_GDCD_GKI", "Thời gian còn lại:"))
        self.B_Button.setText(_translate("Question1_GDCD_GKI", "B. Sản xuất xã hội."))
        self.A_Button.setText(_translate("Question1_GDCD_GKI", "A. Tạo ra của cải vật chất."))
        self.label_3.setText(_translate("Question1_GDCD_GKI", "Tên:"))
        self.label_2.setText(_translate("Question1_GDCD_GKI", "Câu 1. Sản xuất của cải vật chất là quá trình:"))
        self.Next_Button.clicked.connect(Question1_GDCD_GKI.close)

    def ShowTime(self):
        if self.count > 0:
            self.count = self.count - 1
        S1 = str(self.count//60)
        S2 = str(self.count%60)
        S3 = S1 + ":" + S2
        self.Name.setText(str(self.name))
        self.Time.setText(str(S3))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Question1_GDCD_GKI = QtWidgets.QMainWindow()
    ui = Ui_Question1_GDCD_GKI()
    ui.setupUi(Question1_GDCD_GKI)
    Question1_GDCD_GKI.show()
    sys.exit(app.exec_())
